default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: meshiroku_development

test:
  <<: *default
  database: meshiroku_test

production:
  <<: *default
  database: meshiroku_production
  username: meshiroku
  password: <%= ENV['MESHIROKU_DATABASE_PASSWORD'] %>
